// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDLket0WWWvWDLkWWDQIrqyEDrmNblq8',
    appId: '1:584640714822:android:10fae5684bedbcd9895247',
    messagingSenderId: '584640714822',
    projectId: 'flutterblocmvc',
    storageBucket: 'flutterblocmvc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJhsaQ5XJy6yTlfrpT0wjw85CasiP2AUU',
    appId: '1:584640714822:ios:55646712beb32d27895247',
    messagingSenderId: '584640714822',
    projectId: 'flutterblocmvc',
    storageBucket: 'flutterblocmvc.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlocMvc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC1DbGKR3aXIlsnO_3ObyJV0mlocxjXHI',
    appId: '1:584640714822:web:435d2cac5ca9a80c895247',
    messagingSenderId: '584640714822',
    projectId: 'flutterblocmvc',
    authDomain: 'flutterblocmvc.firebaseapp.com',
    storageBucket: 'flutterblocmvc.firebasestorage.app',
  );
}
